### PR TITLE
Added My details

### PR DESCRIPTION
**Pull request by kashirhasnain**
Please review and accept it

### CODE REVIEW

**Comment by khawajaazfar** [comment]
I appreciate your contribution but follow the intruction to add your details , you can not leave all those place empty

**Comment by kashirhasnain** [comment]
you can not leave all those place empty, please identify it

**Comment by khawajaazfar** [comment]
Go to this link and check other contributions:
https://hacktoberfest2022-github.netlify.app/
Your's should be like them to get accepted.

**Comment by kashirhasnain** [comment]
Done

**Comment by khawajaazfar** [comment]
Its not proper , this your contribution right now:
https://deploy-preview-46--hacktoberfest2022-github.netlify.app/
It should be not like this, it  should be like others

**Comment by khawajaazfar** [comment]
Still wrong , i am closing this request, you clone this repo again and then contribute again by reading the readme and following all intruction properly. Use new code

**Pull request closed without merging**
