### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by shiva1217**
Added profile image .

### CODE REVIEW

**Comment by khawajaazfar** [comment]
Still your image tag is not working . Add this open:
https://media-exp1.licdn.com/dms/image/C4D03AQEC1Rtkd6xMHA/profile-displayphoto-shrink_400_400/0/1657009494781?e=1671667200&v=beta&t=E28gBkmHorbtqBZilFb-gxbd0DoRO5XeAWna8NOQEUw

**Comment by shiva1217** [comment]
Sir Done

**Comment by shiva1217** [comment]
Please check.

**Comment by khawajaazfar** [comment]
Great, keep contributing.
You can see deployed here:
https://hacktoberfest2022-github.netlify.app/

**Pull request merged**
