### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by aleenaazeem**
Editing the html file. Added few lines of code.

### CODE REVIEW

**Comment by khawajaazfar** [comment]
You close the pull request ?

**Comment by aleenaazeem** [comment]
I didnt know what i did. :/

**Comment by aleenaazeem** [comment]
Its not merging

**Comment by khawajaazfar** [comment]
Conflict is clear and it's merged. 
You can see deployed it here: 
https://hacktoberfest2022-github.netlify.app/

**Pull request merged**
